#!/usr/bin/env bash

ret=false
getent passwd scope >/dev/null 2>&1 && ret=true

if $ret; then
	sudo -u scope python -m scope.cli.scope_job_daemon "$@"
else
	python -m scope.cli.scope_job_daemon "$@"
fi